<?php

$page_name = $block->getFullActionName();
$tag='';
$json = array();
$alternate = array();
$cartId = $block->getCartId();


/* set the quote start here */

if ($cartId != 0) {
	$record = $block->checkCartId($cartId);

	if($record == 0) {
		if (isset($_COOKIE["cibler_id"])) {
			$block->insertRecord($cartId, $_COOKIE["cibler_id"]);
		}
	}
}

/* set the quote end here */

/* get the cart data section start here */

$cartItems = $block->getCartData();
if($cartItems->getItemsCount())
{
	$items = array();
	$grandTotal = $cartItems->getGrandTotal();

	foreach ($cartItems->getAllItems() as $item) {
		$productId = $item->getProductId();
		$productName = $item->getProduct()->getName();
		$productPrice = $item->getProduct()->getPrice();
		$categoriesIds = $item->getProduct()->getCategoryIds();
		$cartQty = $item->getQty();
		$unitPrice = $item->getPrice();
		$currencyCode = $block->getCurrentCurrencyCode();

		if(count($categoriesIds))
		{
			$categoryId = $categoriesIds[0];
		} else {
			$categoryId = 0;
		}

		$items[] = array("product_id" => $productId,
	      "quantity" => $cartQty,
	      "name" => $productName,
	      "category" => $categoryId,
	      "unit_price" => $unitPrice,
	      "price_currency_code" => $currencyCode);
	}

	$cart_data_array = '"cart":{"total":'.$grandTotal.',"items":'.json_encode($items).'}';
}

/* get the cart data section end here */

/* set data into account pages start here */

$account_pages = array("customer_account_index","customer_account_edit","customer_address_index",
	"sales_order_history","paypal_billing_agreement_index");

if (in_array(trim($page_name), $account_pages)) {
	if(isset($cart_data_array))
	{
		$code=$block->encodeData('{ "page_type":"customer_zone",'.$cart_data_array.'}');
	} else {
		$code=$block->encodeData('{ "page_type":"customer_zone"}');
	}

	$tag='<div id="cibler_context" style="display:none"> '.$code.'</div>';
}

/* set data into account pages end here */

/* product view page content start here */

if ($page_name == 'catalog_product_view') {
	$currentProduct = $block->getCurrentProduct();
	$categoriesIds = $currentProduct->getCategoryIds();
	$product_id = $currentProduct->getId();
	
	if(count($categoriesIds))
	{
		$firstCategoryId = $categoriesIds[0];
		$currentCategoryId = $block->getCurrentCategory()->getId();
	}

	$productStock = $block->getStockItem($currentProduct->getId());

	$productUrl = $currentProduct->getProductUrl();
	$productName = $currentProduct->getName();
	$productImage = $currentProduct->getImage();
	$productPrice = $currentProduct->getPrice();
	$currencyCode = $block->getCurrentCurrencyCode();
	$instock = $productStock->getIsInStock();
	if($instock)
	{
		$stockStatus = "InStock";
	} else {
		$stockStatus = "OutOfStock";
	}
	$productDescription = htmlentities($currentProduct->getDescription());
	$brand = NULL;


	foreach ($currentProduct->getMediaGalleryImages() as $image) {
		$alternate[] = $image->getUrl();
	}

	$productDetail = array(
		"url"=> $productUrl,
		"product_id "=> $product_id,
		"name" => $productName,
		"image_url" => $productImage,
		"price" => $productPrice,
		"price_currency_code" => $currencyCode,
		"availability" => $stockStatus,
		"category" => $currentCategoryId,
		"description" => $productDescription,
		"brand" => NULL,
		"alternate_image_url" => $alternate
    );

	if(isset($cart_data_array))
	{
		$code = $this->encodeData('{ "page_type":"product_page", "product":'.json_encode($productDetail).','. $cart_data_array .'}');
	} else {
		$code = $this->encodeData('{ "page_type":"product_page", "product":'.json_encode($productDetail).'}');        		
	}

	$tag = '<div id="cibler_context" style="display:none"> '.$code.'</div>';
}

/* product view page content end here */

/* Home Page content start here */

if ($page_name == 'cms_index_index') {
	if(isset($cart_data_array))
	{
		$code = $this->encodeData('{ "page_type":"home",'. $cart_data_array .'}');
	} else {
		$code = $this->encodeData('{ "page_type":"home"}');
	}

    $tag = '<div id="cibler_context" style="display:none"> '.$code.' </div>';
}

/* Home Page content end here */

/* Category Page content start here */

if ($page_name == 'catalog_category_view') {
    
	if(isset($cart_data_array))
	{
    	$code = $this->encodeData('{ "page_type":"product_list",'. $cart_data_array .'}');
    } else {
    	$code = $this->encodeData('{ "page_type":"product_list"}');
    }
    $tag = '<div id="cibler_context" style="display:none"> '.$code.' </div>';
}

/* Category Page content end here */

/* Checkout Page content end here */

if ($page_name == 'checkout_cart_index' || $page_name == 'checkout_onepage_index') {
	
	if(isset($cart_data_array))
	{
    	$code = $this->encodeData('{ "page_type":"cart",'. $cart_data_array .'}');
    } else {
    	$code = $this->encodeData('{ "page_type":"cart"}');
    }
   
    $tag = '<div id="cibler_context" style="display:none"> '.$code.' </div>';	
}

/* Checkout Page content end here */

if($tag == '')
{
	if(isset($cart_data_array))
	{
		$code = $this->encodeData('{ "page_type":"showcase",'. $cart_data_array .'}');
	} else {
		$code = $this->encodeData('{ "page_type":"showcase"}');
	}

	echo $tag = '<div id="cibler_context" style="display:none"> '.$code.' </div>';
} else {
	echo $tag; 
}

?>

<script async src="https://cdn.winitout.com/static/<?php echo $block->getCustomerId(); ?>/wio.js"></script>


